# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DesignCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DesignCode
  # Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

  target 'DesignCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DesignCodeUITests' do
    # Pods for testing
  end

end
